In [2]:
import pandas as pd
import numpy as np

In [21]:
df= pd.read_csv('train.csv')
print(pd.DataFrame(df).isna().sum())
df['Age'] = df['Age'].fillna(df['Age'].median())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [22]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [23]:
X=df[['Age','Fare','Pclass']]
Y=df['Survived']

In [24]:
X.head(2)

    Age     Fare  Pclass
0  22.0   7.2500       3
1  38.0  71.2833       1

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

In [36]:
class myLR:
  def __init__(self):
    self.coeff=None
    self.intercept=None
  def fit(self,X_train,Y_train):
    X_train=np.insert(X_train,0,1,axis=1)
    beta = np.linalg.inv(X_train.T @ X_train) @ X_train.T @ Y_train
    self.intercept=beta[0]
    self.coeff=beta[1:]
    print(self.intercept)
    print(self.coeff)

  def predict(self,X_test):
    y_predict = np.dot(X_test, self.coeff) + self.intercept
    print(y_predict)

In [37]:
myLinearReg=myLR()

In [38]:
myLinearReg.fit(X_train,Y_train)

1.029644911006406
[-0.00772358  0.00092404 -0.20121718]

In [39]:
myLinearReg.predict(X_test)

[ 0.52832803  0.27123671  0.50190697  0.26193729  0.30201552  0.20158202
  0.23826255  0.23960317  0.56574614  0.45814601  0.38091023  0.64126567
  0.21719832  0.26193729  0.26193729  0.28650294  0.22382084  0.04753804
  0.30032515 -0.06887793  0.79003077  0.23039304  0.31904875  0.27287687
  0.28548262  0.42855735  0.25073402  0.59172162  0.21851151  0.22307383
  0.27884478  0.14794456  0.4085511   0.65836931  0.5481297   0.2400573
  0.68311769  0.46160704  0.21702918  0.36658769  0.13901185  0.1010329
  0.26323592  0.29297131  0.27159089  0.82240867  0.73826881  0.21773763
  0.2627508   0.42837631  0.21717166  0.45905839  0.44144353  0.50099492
  0.38975842  0.50574582  0.37107304  0.27180268  0.03860921  0.18616185
  0.31483273  0.63578831  0.16310662  0.21643244  0.42021393  0.17989362
  0.48165548  0.43181401  0.45494244  0.30121087  0.25527345 -0.13836703
  0.23204863  0.21693677  0.23243789  0.65552434  0.29440744  0.62806473
  0.49428778  0.23104298  0.76584014  0.65134664  0.09626246  0.38863381
  0.62966827  0.50561209  0.14050185  0.21702918  0.41490795  0.42296282
  0.21687135  0.28678394  0.20917087  0.21702918  0.09347891  0.49571248
  0.29556194  0.32856254  0.21640933  0.68656836  0.96135958  0.31139803
  0.50448748  0.64932498  0.28030014  0.39890281  0.63235361  0.22461015
  0.53493176  0.23054707  0.6398886   0.20919398  0.53230783  0.29264389
  0.93184708  0.41203555  0.22466035  0.66126315  0.59938022  0.43002025
  0.41387853  0.19372372  0.41095036  0.44613355  0.27435927  0.21702918
  0.57714001  0.50448748  0.29415333  0.41095036  0.21702918  0.35839432
  0.32349588  0.70933095  0.2530441   0.22303929  0.33800346  0.21717166
  0.1320968   0.25550446  0.25567405  0.74979691  0.31139803  0.46231227
  0.63670068  0.49912286  0.24420419  0.00477327  0.29417255  0.5001986
  0.55800056  0.20319508  0.19786272  0.10936886  0.21689445  0.15487094
  0.59035921  0.48367571  0.31755896  0.24008829  0.65533576  0.21722942
  0.28668387  0.2093056   0.7094008   0.65671283  0.17026001  0.21691755
  1.03151275  0.2627739   0.22461015  0.29389534  0.43497528  0.2627739
  0.24806598  0.26439096  0.27399983  0.23247633  0.21167732]